changelog:
  categories:
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
        - bugfix
    - title: Documentation
      labels:
        - docs
        - documentation
    - title: Maintenance
      labels:
        - chore
        - ci
        - dependencies
        - refactor
  exclude:
    labels:
      - skip-changelog
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
template: |
  ## What's Changed

  $CHANGES
